# PostgresSQL.  Versions 8.2 recommended.
#
# Fedora Install Instructions:
#   sudo yum install ruby-postgres postgresql-server
#   sudo /sbin/service postgresql initdb
#   sudo /sbin/service postgresql start
#   sudo su - postgres
#   $   psql ovirt
#   $-# CREATE USER ovirt WITH PASSWORD 'v23zj59an';
#   $-# CREATE DATABASE ovirt_development;
#   $-# GRANT ALL PRIVILEGES ON DATABASE ovirt_development to ovirt;
#   $-# CREATE DATABASE ovirt_test;
#   $-# GRANT ALL PRIVILEGES ON DATABASE ovirt_test to ovirt;
#   $-# CREATE DATABASE ovirt;
#   $-# GRANT ALL PRIVILEGES ON DATABASE ovirt to ovirt;
#   $-# \q
#   $   exit
#
# To start off a new environment, use the following commands:
#
#   rake db:drop:all
#   rake db:create:all
#   rake db:migrate
#   rake db:test:prepare
#
# And when there are changes to the database, simple run:
#
#   rake db:migrate
#   rake db:test:prepare
#
#   On a local system you may need to edit this file to have only the following
#   /var/lib/pgsql/data/pg_hba.conf
#   local all all trust
#   host all all 127.0.0.1 255.255.255.255 trust


development:
  adapter: postgresql
  database: ovirt_development
  username: ovirt
  password: v23zj59an
  host: localhost

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: ovirt_test
  username: postgres
  host: localhost

production:
  adapter: postgresql
  database: ovirt
  username: ovirt
  password: v23zj59an
  host: localhost
