development:
  host: management.priv.ovirt.org
  port: 389
  base: dc=priv,dc=ovirt,dc=org

test:
  host: management.priv.ovirt.org
  port: 389
  base: dc=priv,dc=ovirt,dc=org

production:
  host: management.priv.ovirt.org
  port: 389
  base: dc=priv,dc=ovirt,dc=org
